
### GET all users
GET http://localhost:3000/api/users

### GET all reviews
GET http://localhost:3000/api/reviews

###GET review by author
GET http://localhost:3000/api/reviews/12

###GET all categories
GET http://localhost:3000/api/categories


### GET all posts written by 1 user
GET http://localhost:3000/api/posts/5

### GET all posts
GET http://localhost:3000/api/posts

### GET follow user
GET http://localhost:3000/api/users/follows/1

### GET all skills
GET http://localhost:3000/api/skills

### GET proposition
GET http://localhost:3000/api/propositions/12

### GET Unfound user
GET http://localhost:3000/api/users/500