@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoiZXJ3YW5AZ21haWwuY29tIiwiaWF0IjoxNzQ1NTkzNTc5LCJleHAiOjE3NDU2MDA3Nzl9.GsT8F3J3eawb7GEFiQXkpB0PFZJlRsIBfACbG6I0tY4

### Register a user
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "mathieu",
  "lastName": "da fonseca",
  "firstName": "zelitrem",
  "email": "mathieu@gmail.com",
  "password": "Zelitrem1234+",
  "avatar": "",
  "role": "member",
  "description": "Immense nez"
}


###login a user
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "erwan@gmail.com",
  "password": "Erwan1234Mettouchi+"
}


###Test the JWT connexion
GET http://localhost:3000/me
Authorization: Bearer {{token}}

###
GET http://localhost:3000/users

### GET all reviews
GET http://localhost:3000/reviews

###GET review by author
GET http://localhost:3000/reviews/2

###GET all categories
GET http://localhost:3000/categories

###GET all my messages
GET http://localhost:3000/me/messages
Authorization: Bearer {{token}}

###GET messages with user
GET http://localhost:3000/me/messages/14
Authorization: Bearer {{token}}

###
POST http://localhost:3000/me/messages/11
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "message" : "<b>Bonjour 2</b>"
}

### GET all posts written by 1 user
GET http://localhost:3000/posts/4

### GET all posts
GET http://localhost:3000/posts