
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImVtYWlsIjoiZXJ3YW5uQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiRXJ3YW5uIiwiaWF0IjoxNzQ1ODQ2ODc3LCJleHAiOjE3NDU4NTQwNzd9.TX8Q5Tdp3IFVJzFuhkfwlgipimV8SEjCHIr0iRPkCrc


### Register a user
POST http://localhost:3000/register
Content-Type: application/json

{

  "username": "Erwann",
  "lastName": "Mettouchi",
  "firstName": "Erwan",
  "email": "erwann@gmail.com",
  "password": "ErwanMettouchi1234+",
  "avatar": "",
  "role": "member",
  "description": "Travail en boucle"
}


###login a user
POST http://localhost:3000/login
Content-Type: application/json

{

  "email": "erwann@gmail.com",
  "password": "ErwanMettouchi1234+"
}


###Test the JWT connexion
GET http://localhost:3000/me
Authorization: Bearer {{token}}

###
GET http://localhost:3000/users

### GET all reviews
GET http://localhost:3000/reviews

###GET review by author
GET http://localhost:3000/reviews/5

###GET all categories
GET http://localhost:3000/categories

###GET all my messages
GET http://localhost:3000/me/messages
Authorization: Bearer {{token}}

###GET messages with user
GET http://localhost:3000/me/messages/13
Authorization: Bearer {{token}}

###
POST http://localhost:3000/me/messages/13
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "message" : "<b>Bonjour 3</b>"
}

### GET all posts written by 1 user
GET http://localhost:3000/posts/5

### GET all posts
GET http://localhost:3000/posts

### GET all posts
GET http://localhost:3000/me/posts
Authorization: Bearer {{token}}

### create new post
POST http://localhost:3000/me/posts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "",
  "content" : "",
  "skill_id" : 11
}

###
GET http://localhost:3000/users/follows/1

###
GET http://localhost:3000/me/follows
Authorization: Bearer {{token}}

###
GET http://localhost:3000/skills

###
GET http://localhost:3000/propositions/1




################ USER PROFILES #######################

### 1. Normal Update
PATCH http://localhost:3000/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "ErwanMisAJour",
  "description": "Nouvelle description après mise à jour"
}

###
### Fail to change already Used email
PATCH http://localhost:3000/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "mathieu@gmail.com"
}

###
### Empty request should fail
PATCH http://localhost:3000/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
}

### Update All fields at once
PATCH http://localhost:3000/me

###
GET http://localhost:3000/users/500

###
GET http://localhost:3000/me/users
Authorization: Bearer {{token}}

###
GET http://localhost:3000/me/propositions
Authorization: Bearer {{token}}

###
POST http://localhost:3000/me/propositions/5
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content" : ""
}