@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoiZXJ3YW5AZ21haWwuY29tIiwidXNlcm5hbWUiOiJFcndhbiIsImlhdCI6MTc0NTgzOTAxNywiZXhwIjoxNzQ1ODQ2MjE3fQ.LMvBGr2rz_221oA4dHBqGbi1k18qWHS_rkFQM7qbqwQ
### Register a user
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "Erwan",
  "lastName": "Mettouchi",
  "firstName": "Erwan",
  "email": "erwan@gmail.com",
  "password": "ErwanMettouchi1234+",
  "avatar": "",
  "role": "member",
  "description": "Travail en boucle"
}


###login a user
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "erwan@gmail.com",
  "password": "ErwanMettouchi1234+"
}


###Test the JWT connexion
GET http://localhost:3000/me
Authorization: Bearer {{token}}

###
GET http://localhost:3000/users

### GET all reviews
GET http://localhost:3000/reviews

###GET review by author
GET http://localhost:3000/reviews/5

###GET all categories
GET http://localhost:3000/categories

###GET all my messages
GET http://localhost:3000/me/messages
Authorization: Bearer {{token}}

###GET messages with user
GET http://localhost:3000/me/messages/5
Authorization: Bearer {{token}}

###
POST http://localhost:3000/me/messages/5
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "message" : "<b>Bonjour 3</b>"
}

### GET all posts written by 1 user
GET http://localhost:3000/posts/50

### GET all posts
GET http://localhost:3000/posts

### GET all posts
GET http://localhost:3000/me/posts
Authorization: Bearer {{token}}

### create new post
POST http://localhost:3000/me/posts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "J'aimerais apprendre React!",
  "content" : "<b>Bonjour 2</b>",
  "skill_id" : 11
}

###
GET http://localhost:3000/users/follows/50

###
GET http://localhost:3000/me/follows
Authorization: Bearer {{token}}

###
GET http://localhost:3000/skills

###
GET http://localhost:3000/propositions/1






################ USER PROFILES #######################

### 1. Normal Update
PATCH http://localhost:3000/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "ErwanMisAJour",
  "description": "Nouvelle description après mise à jour"
}

###
### Fail to change already Used email
PATCH http://localhost:3000/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "mathieu@gmail.com"
}

###
### Empty request should fail
PATCH http://localhost:3000/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
}

### Update All fields at once
PATCH http://localhost:3000/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "ErwanTotalUpdate",
  "firstname": "Erwanupdated",
  "lastname": "Metouchi2",
  "email": "erwan2@gmail.com",
  "avatar": "/avatars/avatar2.png",
  "description": "Je suis toujours en train de bosser update"
}



